dist: bionic
language: python
python:
  - "3.7"

addons:
  postgresql: "11"

services:
  - redis
  - postgres

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.cache/pip
    - DATABASE_URL=pgsql://postgres:turnout@localhost:5432/turnout
    - REDIS_URL=redis://localhost:6379
    - SECRET_KEY=turnoutallthepeople
    - DJANGO_SETTINGS_MODULE=turnout.settings

before_install:
  - pip install --upgrade pip
  - psql -c "ALTER USER postgres WITH PASSWORD 'turnout'"

install:
  - pip install -r $TRAVIS_BUILD_DIR/app/requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:/$TRAVIS_BUILD_DIR/app

script:
  - pytest $TRAVIS_BUILD_DIR/app
  - mypy --config-file $TRAVIS_BUILD_DIR/app/setup.cfg $TRAVIS_BUILD_DIR/app

notifications:
  email: false

deploy:
  - provider: script
    script: bash scripts/travis_deploy_tags.sh
    on:
      tags: true
      all_branches: true
      repo: vote/turnout
  - provider: script
    script: bash scripts/travis_deploy_master.sh
    on:
      branch: master
      repo: vote/turnout
