# Generated by Django 2.2.12 on 2020-04-10 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    replaces = [('official', '0001_initial'), ('official', '0002_address_office'), ('official', '0003_auto_20200410_2042'), ('official', '0004_auto_20200410_2047'), ('official', '0005_address_zipcode')]

    initial = True

    dependencies = [
        ('election', '0004_updatenotificationwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_updated', models.DateTimeField(null=True)),
                ('external_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('municipality', models.TextField(db_index=True, null=True)),
                ('municipality_type', models.TextField(null=True)),
                ('county', models.TextField(db_index=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.State')),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_updated', models.DateTimeField(null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='official.Region')),
                ('hours', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('website', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_updated', models.DateTimeField(null=True)),
                ('city', models.TextField(null=True)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='official.Office')),
                ('address', models.TextField(null=True)),
                ('address2', models.TextField(null=True)),
                ('address3', models.TextField(null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.State')),
                ('process_absentee_ballots', models.BooleanField(default=False)),
                ('process_absentee_requests', models.BooleanField(default=False)),
                ('process_domestic_registrations', models.BooleanField(default=False)),
                ('process_overseas_ballots', models.BooleanField(default=False)),
                ('process_overseas_requests', models.BooleanField(default=False)),
                ('zipcode', models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
            ],
            options={
                'abstract': False,
                'ordering': ['external_id'],
            },
        ),
    ]
