# Generated by Django 2.2.12 on 2020-04-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0004_updatenotificationwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_updated', models.DateTimeField(null=True)),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.TextField(null=True)),
                ('municipality', models.TextField(db_index=True, null=True)),
                ('municipality_type', models.TextField(null=True)),
                ('county', models.TextField(db_index=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.State')),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
    ]
