# Generated by Django 2.2.12 on 2020-04-10 21:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_squashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='email',
        ),
        migrations.RemoveField(
            model_name='office',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='office',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='office',
            name='website',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='address',
            name='is_physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_regular_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
