# Generated by Django 2.2.12 on 2020-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_auto_20200410_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
